# Generated by Django 2.1 on 2018-10-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
    ]
