# Generated by Django 2.1 on 2018-10-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_gbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gbook',
            name='post',
        ),
    ]
