# Generated by Django 2.1.2 on 2018-11-16 02:58

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_gbook_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
