# Generated by Django 2.1.2 on 2018-11-15 11:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_gbook_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
